const ProductsList = [
  {
    id: 1,
    heading: "WE",
    perfume: "/rectangle-223-797@2x.png",
    heading1: "PERFUME BOX",
    para: "Unveil elegance with our  box packaging - a treasure trove of luxury in every detail",
    headingPadding: null,
    frameDivColor: null,
    paraTransform: null,
  },
  {
    id: 2,
    heading: "DESIGN",
    perfume: "/incense@2x.png",
    heading1: "INCENSE STICK BOX",
    para: "Unlock tranquility with our incense stick box – a sanctuary of serene scents",
    headingPadding: "0px 0px 68px",
    frameDivColor: "#7cbd8e",
    paraTransform: "scale(1.471)",
  },
  {
    id: 3,
    heading: "PACKAGE",
    perfume: "/rectangle-225-813@2x.png",
    heading1: "FOOD PACKAGING",
    para: "Savor freshness with every unwrap of our food packaging.",
    headingPadding: "0px 0px 68px",
    frameDivColor: "#CE4D74",
    paraTransform: "scale(1.471)",
  },
];

const CarouselList = [
  {
    id: 1,
    heading: "WE",
    perfume: "/rectangle-223-797@2x.png",
    heading1: "PERFUME BOX",
    para: "Unveil elegance with our  box packaging - a treasure trove of luxury in every detail",
    headingPadding: null,
    frameDivColor: null,
    paraTransform: null,
  },
  {
    id: 2,
    heading: "DESIGN",
    perfume: "/incense@2x.png",
    heading1: "INCENSE STICK BOX",
    para: "Unlock tranquility with our incense stick box – a sanctuary of serene scents",
    headingPadding: "0px 0px 68px",
    frameDivColor: "#7cbd8e",
    paraTransform: "scale(1.471)",
  },
  {
    id: 3,
    heading: "PACKAGE",
    perfume: "/rectangle-225-813@2x.png",
    heading1: "FOOD PACKAGING",
    para: "Savor freshness with every unwrap of our food packaging. testing for doing component",
    headingPadding: "0px 0px 68px",
    frameDivColor: "#CE4D74",
    paraTransform: "scale(1.471)",
  },
  {
    id: 4,
    heading: "PACKAGE",
    perfume: "/rectangle-225-813@2x.png",
    heading1: "FOOD PACKAGING",
    para: "Savor freshness with every unwrap of our food packaging. testing for doing component",
    headingPadding: "0px 0px 68px",
    frameDivColor: "#CE4D74",
    paraTransform: "scale(1.471)",
  },
];

export { ProductsList, CarouselList };
