[build]
  publish = "dist" # Change to your output directory if different
  command = "npm run build" # Ensure this matches your build command

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
